version: '3.8'
services:
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SECURE_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: reminder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  reminder:
    image: reminder-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/reminder"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${SECURE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REMINDER_NOTIFICATIONS_EMAIL_SMTP_HOST: ${SMTP_HOST}
      REMINDER_NOTIFICATIONS_EMAIL_SMTP_PORT: ${SMTP_PORT}
      REMINDER_NOTIFICATIONS_EMAIL_SMTP_LOGIN: ${SMTP_LOGIN}
      REMINDER_NOTIFICATIONS_EMAIL_SMTP_FROM: ${SMTP_LOGIN}
      REMINDER_NOTIFICATIONS_EMAIL_SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
