version: '3.8'
services:
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SECURE_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: reminder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
