spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  web:
    resources:
      static-locations: file:/opt/static
reminder:
  scheduler:
    interval.s: 10

